### ISSUE TITLE
Create a plugin to provide a course export API

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/open-edx-plugins#27]
As part of our data pipelines we need to be able to export the course contents as OLX. In order to make this more manageable in a proper orchestration approach we want to create an API endpoint that takes a course ID as an input and exports the course to an S3 bucket. This API should respond with the location that the file will be exported to. As an optional enhancement, it would be useful to allow passing in a list of course IDs and exporting all of them to the same location.

There is already a majority of the code needed to support this use case.

Code to export a course tarball: https://github.com/edx/edx-platform/blob/open-release%2Fmaple.master/cms/djangoapps/contentstore/tasks.py#L332
An API view for course import: https://github.com/edx/edx-platform/blob/open-release%2Fmaple.master/cms/djangoapps/contentstore/api/views/course_import.py

**Comment by blarghmatey** [comment]
The immediate use case is for being able to install this in our existing edX deployments to be consumed by our own internal service. As such we can just build the functionality, deploy and validate it, and add tests as a second step. Eventually we might want to contribute this functionality upstream, but that is not a requirement for the initial work.

**Comment by arslanashraf7** [comment]
So the synchronous course upload was intended to see this being run inside a pipeline and look for the s3 bucket URLs as a response upon the API call. Mentioned also in the [Reviewer Note](https://github.com/mitodl/open-edx-plugins/pull/29#issue-1132118020).

**If we are looking to change the behavior:**
>Is there an available interface for defining a task inside a plugin?

Looking at a few references e.g. [Django App Plugins](https://github.com/openedx/edx-django-utils/tree/master/edx_django_utils/plugins), [Plugin Contexts](https://github.com/openedx/edx-django-utils/blob/master/edx_django_utils/plugins/docs/decisions/0001-plugin-contexts.rst) I don't think there is any interface right away as part of the plugin configuration to define a Task.

>Alternatively, how difficult will it be to defer the heavy lifting to Celery?

Looking at how [course import](https://github.com/openedx/edx-platform/blob/open-release%2Fmaple.master/cms/djangoapps/contentstore/api/views/course_import.py#L150-L154) is working, It is also starting celery task to perform the import operation for a single course only. And I think we might do something similar too.


>This API should respond with the location that the file will be exported to.

_**But,**_ As mentioned in the ticket description, This will change the behavior of the API itself, The course import view gives 2 APIs 
1) POST - for starting a celery task for a course ID and then returning the task id for future progress updates 
2) GET - For returning the progress. of the task.

Also, this uses another model [CourseImportTask](https://github.com/openedx/edx-platform/blob/master/cms/djangoapps/contentstore/tasks.py#L427) that keeps the states of the task to return upon a GET request.

We can try the above solution if we are good with changing the intended behavior of the API as mentioned above.

@blarghmatey What would your yout thoughts be on above?

**Comment by pdpinch** [comment]
I’m pretty sure that the user-initiated export in studio is asynchronous. Is there a task we  an reuse in that code?

**Comment by arslanashraf7** [comment]
> I’m pretty sure that the user-initiated export in studio is asynchronous. Is there a task we an reuse in that code?

In fact, it does. The course export API [starts the task here](https://github.com/openedx/edx-platform/blob/master/cms%2Fdjangoapps%2Fcontentstore%2Fviews%2Fimport_export.py#L337). The task itself looks [can be seen here](https://github.com/openedx/edx-platform/blob/master/cms/djangoapps/contentstore/tasks.py#L292-L329).

This export operation behaves similar to the import operation and starts celery tasks. But looking at that it doesn't look like we can reuse it since we only need to generate the course tarball and not save it locally, instead upload to S3. We might be able to create a similar behavior but the API would become:
1) POST call, starts the tasks for exporting multiple course at the same time and return Task IDs
2) GET call, to check the status of the tasks (Failes, In progress, Succeeded etc.)

**Comment by blarghmatey** [comment]
I think that from an API design perspective, we should either modify it to only accept one course at a time, or accept a list of courses and export them asynchronously.

**Comment by arslanashraf7** [comment]
@blarghmatey, I am now inclined to believe that even if we accept one course and assume the course size is big enough we can still see the timeout error on it since this is just an API and it will timeout based on the request timeout value.

So, As mentioned above and keeping in mind the current design of edX for Course Import and & local export, I will try to enhance the plugin to upload the course in a celery task with a structure of (GET, POST) requests.

_POST_ for posting course IDs to start the upload and return the task Ids. (I can still return a URL of s3 since we are already generating it ourselves in the current implementation, but that won't guarantee that the upload was successful)

_GET_ to get the status of a specific task

**Comment by pdpinch** [comment]
Can this issue be closed now?
